# Wuhan-Hu-1 "reference" spike protein
ref_spike: YP_009724390

# parent specs and how many mutants of each design
parent_specs:
  XBB.1.5:
    specs: parent_specs/XBB.1.5.yaml
    nmutants: 5
  
# design categories and number of mutations per spike in each category
categories:
  moderate: 6 
  aggressive: 12

# allow reversions to the Wuhan-Hu-1 reference
allow_reversions_to_ref: false

# each time a mutation gets included in a mutant for a parent / category, downweight it this much
# to encourage new mutations be included in subsequent mutants
repetition_downweight: 0.5
