# Wuhan-Hu-1 "reference" spike protein
ref_spike: YP_009724390
rbd_coords: [331, 528]  # start end of RBD in reference, inclusive

# file defining Pango clades
pango_json: https://raw.githubusercontent.com/corneliusroemer/pango-sequences/main/data/pango-consensus-sequences_summary.json

# parent specs and how many mutants of each design
parent_specs:
  KP.2:  # fastest growing JN.1-descended lineage as of May-1-2024 from https://nextstrain.github.io/forecasts-ncov/
    specs: parent_specs/KP.2.yaml
    nmutants: 4
  HK.3.2:  # one of the fastest growing remaining XBB lineages
    specs: parent_specs/HK.3.2.yaml
    nmutants: 2
  
# design categories and number of mutations per spike in each category
categories:
  moderate: 5 
  aggressive: 8

# allow reversions to the Wuhan-Hu-1 reference
allow_reversions_to_ref: false

# each time a mutation gets included in a mutant for a parent / category, downweight it this much
# to encourage new mutations be included in subsequent mutants
repetition_downweight: 0.3

# URL to get escape calculator module
escape_calculator_module_url: https://raw.githubusercontent.com/jbloomlab/SARS2-RBD-escape-calc/6d56b7d0b353ddf7b107eb63b50124826d476dee/escapecalculator.py

# output file
designed_mutants: designed_mutants.csv