name: SARS2-RBD-escape-mutants
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - altair=5.3
  - biopython=1.83
  - jupyterlab
  - pandas=2.2
  - pip
  - pyarrow
  - python=3.12
  - ruamel.yaml=0.18.6
